--- #Testing
- name: Settings
  hosts: localhost
  gather_facts: true
  collections:
  - purestorage.flasharray
#  vars_files:
#    - mig-vars.yaml
  tasks:
  - name: Create snapshot of volume foo
    purefa_snap:
      fa_url: "10.132.2.60"
      api_token: "de1d625c-cf1b-10fc-2606-90285d4de627"
      name: foo
      suffix: ansible
      state: present

  - name: Create 1st clone from snap of foo (foo.snap)
    purefa_snap:
      fa_url: "10.132.2.60"
      api_token: "de1d625c-cf1b-10fc-2606-90285d4de627"
      name: foo
      suffix: ansible
      target: foo_clone1
      state: copy

  - name: Create 2nd clone from snap of foo (foo.snap)
    purefa_snap:
      fa_url: "10.132.2.60"
      api_token: "de1d625c-cf1b-10fc-2606-90285d4de627"
      name: foo
      suffix: ansible
      target: foo_clone2
      state: copy

  - name: Create 3rd clone from snap of foo (foo.snap)
    purefa_snap:
      fa_url: "10.132.2.60"
      api_token: "de1d625c-cf1b-10fc-2606-90285d4de627"
      name: foo
      suffix: ansible
      target: foo_clone3
      state: copy
